#!/bin/bash

set -euo pipefail

if command -v zsh >/dev/null; then
    sudo chsh -s "$(command -v zsh)" "$USER"
fi


if ! command -v chezmoi >/dev/null; then
    sh -c "$(curl -fsLs get.chezmoi.io)" -- init --apply https://github.com/treenester/dev-dotfiles.git
fi

if [ ! -d "$HOME/.zsh" ]; then
    mkdir -p "$HOME/.zsh"
fi

# zsh auto-suggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# zsh syntax highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# zsh fzf-tab
git clone https://github.com/Aloxaf/fzf-tab ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/fzf-tab
